# Generated by Django 3.2.5 on 2023-08-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCatPiece', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUser', models.CharField(max_length=100)),
                ('prenomUser', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Non-binaire', 'Non-binaire')], max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomVehCat', models.CharField(max_length=100)),
                ('descriptionVehCat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('numPlaque', models.CharField(max_length=20)),
                ('nombreCylindres', models.PositiveIntegerField()),
                ('typeBoiteVitesse', models.BooleanField(default=False)),
                ('assurance', models.BooleanField(default=False)),
                ('numChassis', models.CharField(max_length=100)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCommande', models.DateTimeField(auto_now_add=True)),
                ('statutCommande', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomItem', models.CharField(max_length=100)),
                ('descriptionItem', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statutItem', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.categorypieces')),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomGarage', models.CharField(max_length=100)),
                ('adresseGarage', models.CharField(max_length=200)),
                ('localisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.location')),
            ],
        ),
        migrations.CreateModel(
            name='detailOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitePiece', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.order')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.item')),
            ],
        ),
        migrations.CreateModel(
            name='detailCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteCart', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.item')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.user'),
        ),
    ]
