# Generated by Django 3.2.5 on 2023-08-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypieces',
            name='nomCatPiece',
            field=models.CharField(choices=[('Mécanique', 'Mécanique'), ('Electrique', 'Electrique')], max_length=31),
        ),
    ]
