# Generated by Django 3.2.5 on 2023-08-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0003_alter_vehiclecategory_nomvehcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='nomVehCat',
            field=models.CharField(choices=[('Mini-citadines', 'Mini-citadines'), ('Petites voitures', 'Petites voitures'), ('Voitures compactes', 'Voitures compactes'), ('Grosses voitures', 'Grosses voitures'), ('Voitures de prestige', 'Voitures de prestige'), ('Voitures de luxe', 'Voitures de luxe'), ('SUV', 'SUV'), ('Grandes voitures familiales', 'Grandes voitures familiales'), ('Voitures de sport', 'Voitures de sport'), ('Je ne sais pas', 'Je ne sais pas')], max_length=100),
        ),
    ]
