# Generated by Django 3.2.5 on 2023-09-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0004_alter_vehiclecategory_nomvehcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='marque',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
