# Generated by Django 3.2.5 on 2023-10-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0005_item_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemCart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='quantiteItems',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='marque',
            field=models.CharField(default='Toutes les marques', max_length=100),
        ),
    ]
