# Generated by Django 3.2.5 on 2023-10-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0006_auto_20231006_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypieces',
            name='nomCatPiece',
            field=models.CharField(choices=[('Mécanique', 'Mécanique'), ('Electrique', 'Electrique'), ('Accessoire', 'Accessoire')], max_length=31),
        ),
    ]
