# Generated by Django 3.2.5 on 2023-10-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0007_alter_categorypieces_nomcatpiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imageItem',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
