# Generated by Django 3.2.5 on 2023-12-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0008_item_imageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='numeroGarage',
            field=models.IntegerField(default=90002522),
            preserve_default=False,
        ),
    ]
