# Generated by Django 3.2.5 on 2023-12-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0009_garage_numerogarage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statutCommande',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Finalisée', 'Finalisée'), ('En attente', 'En attente')], default='En attente', max_length=20),
        ),
    ]
