# Generated by Django 3.2.5 on 2023-12-08 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0010_alter_order_statutcommande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='localisation',
        ),
        migrations.AddField(
            model_name='garage',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=6.13748, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garage',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=6, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garage',
            name='quartier',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garage',
            name='ville',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
