# Generated by Django 3.2.5 on 2023-12-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0011_auto_20231208_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='quartier',
        ),
    ]
