# Generated by Django 3.2.5 on 2023-12-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0012_remove_garage_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statutCommande',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Finalisée', 'Finalisée'), ('En attente', 'En attente'), ('Rejetee', 'Rejetee')], default='En attente', max_length=20),
        ),
    ]
