# Generated by Django 3.2.5 on 2023-12-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0013_alter_order_statutcommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=9005, max_length=128),
            preserve_default=False,
        ),
    ]
