# Generated by Django 3.2.5 on 2023-12-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0015_auto_20231213_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='order',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='utilisateur',
        ),
    ]
