# Generated by Django 3.2.5 on 2023-12-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0016_auto_20231213_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
