# Generated by Django 3.2.5 on 2023-12-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0017_garage_quartier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='quartier',
        ),
    ]
