# Generated by Django 3.2.5 on 2023-12-14 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venteVoiture', '0018_remove_garage_quartier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
