# Generated by Django 3.2.5 on 2023-12-14 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0019_order_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.vehiclecategory'),
            preserve_default=False,
        ),
    ]
