# Generated by Django 3.2.5 on 2023-12-14 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0021_vehicle_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voiture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.vehicle'),
            preserve_default=False,
        ),
    ]
