# Generated by Django 3.2.5 on 2023-12-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0022_order_voiture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorder',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='venteVoiture.order'),
        ),
    ]
