# Generated by Django 3.2.5 on 2023-12-17 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0023_alter_detailorder_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorder',
            name='piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.item'),
        ),
    ]
