# Generated by Django 3.2.5 on 2023-12-17 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0024_alter_detailorder_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorder',
            name='piece',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.item'),
            preserve_default=False,
        ),
    ]
