# Generated by Django 3.2.5 on 2023-12-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0025_alter_detailorder_piece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailorder',
            name='piece',
        ),
    ]
