# Generated by Django 3.2.5 on 2023-12-18 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0026_remove_detailorder_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailorder',
            name='piece',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='venteVoiture.item'),
            preserve_default=False,
        ),
    ]
