# Generated by Django 3.2.5 on 2023-12-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0027_detailorder_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paye',
            field=models.BooleanField(default=False),
        ),
    ]
