# Generated by Django 3.2.5 on 2023-12-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venteVoiture', '0028_order_paye'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='motif',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
